# Generated by Django 5.2.1 on 2025-05-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seats', models.IntegerField()),
                ('early_bird_enabled', models.BooleanField(default=False)),
                ('dynamic_pricing_enabled', models.BooleanField(default=False)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
